### ISSUE TITLE
Image aquisition fails on second frame

### ISSUE THREAD

**Issue by dee-sea** [indilib/indi-3rdparty#824]
**Describe the bug**
I've two POA cameras, a Ceres-C and a Saturn-C. With my Ceres-C everything works as expected but with the Saturn-C every second exposure hangs in the capturing state. If a abort the exposure and restart the sequence or start a new capture that works again once and then the next capture fails again. If I abort the  second capture (the one who is failing), even before it finishes, then the next one succeeds again.

I already did some debuging an it appears that the call to POAImageReady near the end of the exposure loop never set pIsReady to POA_TRUE for the second capture but do it for the first capture.

An other hint I've found so far, is that if I set the last argument of POAStartExposure to POA_FALSE instead of POA_TRUE and add a POAStopExposure after the call to grabImage, the capture succueds but take twice as long as the time set for the exposure to finish. Given the poor documentation I found for the POA sdk, I don't understand what that boolean changes in the process. It's only stated that as to be set to false for video mode and to true for single image capture but that it's possible to set it to false for "short single image capture" (perhaps because of the twice as long time it takes), not really sure about that as the doc I found only provides examples and no real explanation of what the functions do and what the parameters are for.

I'm also in touch with Sean Wang for POA by email to try to solve this.

**To Reproduce**
Exact steps to reproduce the behavior.
1. Run driver with a Saturn-C camera
2. Start two capures in a row
3. See that the second captures hangs

**Expected behavior**
All captures should complete successfully

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Stellarmate 1.7.8 (with indi-playerone-ccd and libplayerone compiled from the master branch for debuging)

**Log Files**
Log don't show any errors

**Comment by dee-sea** [comment]
@hiro3110i I've seen in another thread that you don't have a Saturn-C. I can give you access to my setup if needed.

**Comment by hiro3110i** [comment]
@dee-sea Thank you for reporting.
I tried to reproduce your issue with the latest driver (indi v2.0.3 and indi_playerone_ccd v1.10) on my Raspberry Pi4.
I'm using KStars/Ekos on Ubuntu Mate 22.04/64bit, not Stellarmate OS.

I didn't have any issue with main=Poseidon-C Pro and guide=Sedna-M.
And main=Uranus-C and guide=Neptune-C II (as a mono camera with IR pass filter) have no issue.
I always use Ekos with these combinations for deep sky imaging.

Further investigation is required to see if there are any problems specific to Saturn-C.
I have started discussion with PlayerOne engineers.
Please give me time to reach a conclusions.

Could you please check just simple things?
(1)  Optical train settings
     I saw same kind of hang up during exposure loop when I set same camera device to primary and secondary simultaneously.
     Sometime that settings are changed unconsciously. (in my case)
(2) 'Controls' tab of INDI Control Panel
     'USBBandWidthLimit' should be less than 50 when we use two cameras simultaneously.
     Typically around 35 is recommended.
I'm very sorry if you've already checked it.

And thank you so much for code reviewing.
In the past investigations, I also discussed on your point with PlayerOne engineers.
But current description is more suitable for single frame capture,
even in the sequential capture because it is continuous one shot capture, not video capture.

That is a quick answer at this moment.
Your understanding will be appreciated.

**Comment by dee-sea** [comment]
@hiro3110i  Thanks for you rapid answer.

I've already checked the optical train settings an Jasem made a remote connection too to control my settings.

I've also played with different values for the USB Bandwidth as it's mentionned in the notes section of the readme file.

By the way, I've also check with only the saturn-c commera connected and the issue is the same event without the Ceres-C and the mount.

**Comment by dee-sea** [comment]
And feel free to ask, I'm not well used to kstar/ekos/indilib, I can make dumb mistakes there, but i'm a computer engineer and a long time linux user. My cpp skills are quite rusty now but I also have a programming background, C and perl historically and mostly python and some rust today.

**Comment by dee-sea** [comment]
May I suggest what I think is a  small improvement here or should I open another thread?

During my investigation of the POA sdk, I noticed that the last argument of POAGetImageData is a value for a timeout after which the function will return with an error if it was not possible to get the image from the camera. In the driver the value is set to -1 which mean wait forever. As the driver, already waits for the data to be ready with the loop updating the timer and calling POAImageReady, the data should already be ready when POAGetImageData is called so setting the timeout to 1 or two seconds will be OK. For debugging purposes and even in normal use it's better to have a function returning an error than getting stuck and never returning.

Perhaps there will be some not to bad sky tonight here, I'm crossing fingers to be able to have 1 or 2 hours to test it tonight.

**Comment by dee-sea** [comment]
I had just enough time to test the camera with the new firmware to night before the clouds came. Everything is fine.

Thank you for helping me solve this problem and I apologize for any inconvenience.
